-- EBB Phase 1 schema
-- Run this in the Supabase SQL editor before enabling the mobile auth flow.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text not null default 'EBB Listener',
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.playlists (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  cover_color_value bigint,
  cover_image_path text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.playlist_tracks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  playlist_id text not null references public.playlists (id) on delete cascade,
  position integer not null check (position >= 0),
  track_id text,
  track_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.play_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  track_id text not null,
  event_type text not null default 'play',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  check (event_type in ('play', 'pause', 'skip', 'complete', 'download'))
);

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  query text not null check (char_length(trim(query)) between 1 and 200),
  result_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.library_tracks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  track_id text not null,
  track_data jsonb not null default '{}'::jsonb,
  added_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists playlists_user_id_id_idx
  on public.playlists (user_id, id);

create unique index if not exists playlist_tracks_user_playlist_position_idx
  on public.playlist_tracks (user_id, playlist_id, position);

create index if not exists playlist_tracks_user_playlist_idx
  on public.playlist_tracks (user_id, playlist_id);

create index if not exists play_events_user_created_idx
  on public.play_events (user_id, created_at desc);

create index if not exists play_events_user_track_idx
  on public.play_events (user_id, track_id);

create index if not exists search_events_user_created_idx
  on public.search_events (user_id, created_at desc);

create unique index if not exists library_tracks_user_track_idx
  on public.library_tracks (user_id, track_id);

create index if not exists library_tracks_user_added_idx
  on public.library_tracks (user_id, added_at desc);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists playlists_set_updated_at on public.playlists;
create trigger playlists_set_updated_at
before update on public.playlists
for each row execute procedure public.set_updated_at();

drop trigger if exists library_tracks_set_updated_at on public.library_tracks;
create trigger library_tracks_set_updated_at
before update on public.library_tracks
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, 'ebb-listener'), '@', 1)
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    )
  )
  on conflict (id) do update
  set
    email = excluded.email,
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.play_events enable row level security;
alter table public.search_events enable row level security;
alter table public.library_tracks enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "playlists_manage_own" on public.playlists;
create policy "playlists_manage_own"
on public.playlists
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "playlist_tracks_manage_own" on public.playlist_tracks;
create policy "playlist_tracks_manage_own"
on public.playlist_tracks
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "play_events_manage_own" on public.play_events;
create policy "play_events_manage_own"
on public.play_events
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "search_events_manage_own" on public.search_events;
create policy "search_events_manage_own"
on public.search_events
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "library_tracks_manage_own" on public.library_tracks;
create policy "library_tracks_manage_own"
on public.library_tracks
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
