from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Tuple

from ..domain.catalog import (
    catalog_source_authority,
    normalize_album_title,
    normalize_artist_name,
    normalize_track_title,
    normalized_popularity,
)
from ..domain.result_quality import track_result_penalty
from .server_adapter import SearchServerAdapter


@dataclass(frozen=True)
class CanonicalSearchDiagnostics:
    query_key: str
    resolved_title: str
    resolved_artist: str
    entity_confidence: float
    entity_vote_count: int
    entity_candidate_count: int
    top_source_quality: float
    canonical_backend: str = "canonical_entity_resolver_v1"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "canonical_backend": self.canonical_backend,
            "canonical_query_key": self.query_key,
            "canonical_resolved_title": self.resolved_title,
            "canonical_resolved_artist": self.resolved_artist,
            "canonical_entity_confidence": round(self.entity_confidence, 4),
            "canonical_entity_vote_count": self.entity_vote_count,
            "canonical_entity_candidate_count": self.entity_candidate_count,
            "canonical_top_source_quality": round(self.top_source_quality, 4),
        }


@dataclass(frozen=True)
class CanonicalSearchResult:
    tracks: List[Dict[str, Any]]
    diagnostics: CanonicalSearchDiagnostics


def _text(value: Any) -> str:
    return str(value or "").strip()


def _field_text(item: Dict[str, Any], keys: Iterable[str]) -> str:
    for key in keys:
        value = _text(item.get(key))
        if value:
            return value
    return ""


def _source_text(server: SearchServerAdapter, item: Dict[str, Any]) -> str:
    return server.normalize_text(
        " ".join(
            _text(item.get(key))
            for key in (
                "provider",
                "source",
                "source_name",
                "artist",
                "artist_name",
                "channel",
                "author",
                "uploader",
                "uploader_id",
                "description",
            )
        )
    )


def _has_structured_identity(item: Dict[str, Any]) -> bool:
    return any(
        _text(item.get(key))
        for key in (
            "album_id",
            "albumId",
            "artist_id",
            "artistId",
            "channel_id",
            "channelId",
            "browseId",
        )
    )


def _learned_popularity(item: Dict[str, Any]) -> float:
    try:
        value = float(item.get("learned_popularity") or 0.0)
    except (TypeError, ValueError):
        value = 0.0
    return max(0.0, min(value, 1.0))


def source_quality_score(server: SearchServerAdapter, item: Dict[str, Any]) -> float:
    text = _source_text(server, item)
    score = 0.0
    identity_authority = server.normalize_text(item.get("source_identity_authority")).replace(" ", "_")
    identity_confidence = 0.0
    try:
        identity_confidence = float(item.get("source_identity_confidence") or 0.0)
    except (TypeError, ValueError):
        identity_confidence = 0.0
    if identity_authority in {"vevo", "topic", "official_artist_channel"}:
        score += min(0.9, 0.25 + identity_confidence)
    elif identity_authority in {"album_relation", "verified_catalog"}:
        score += min(0.65, 0.2 + (identity_confidence * 0.65))
    elif identity_authority == "user_upload" and identity_confidence >= 0.5:
        score -= 0.15
    explicit = server.normalize_text(item.get("source_authority")).replace(" ", "_")
    if explicit == "search_only":
        score -= 1.0
    elif explicit == "canonical":
        score += 0.75
    elif explicit == "verified_catalog":
        score += 0.65
    elif explicit == "official":
        score += 0.35
    if _has_structured_identity(item):
        score += 0.55
    if "vevo" in text:
        score += 0.75
    if " topic" in text or "- topic" in text:
        score += 0.55
    if "provided to youtube" in text or "auto generated by youtube" in text or "auto-generated by youtube" in text:
        score += 0.55
    if "official" in text:
        score += 0.18 if score > 0 else -0.15
    authority = catalog_source_authority(item)
    if authority == "search_only":
        score -= 1.0
    elif authority == "verified_catalog":
        score += 0.45
    elif authority == "canonical":
        score += 0.35
    return max(-1.0, min(score, 1.8))


def source_has_authoritative_marker(server: SearchServerAdapter, item: Dict[str, Any]) -> bool:
    text = _source_text(server, item)
    if _has_structured_identity(item):
        return True
    return any(
        marker in text
        for marker in (
            "vevo",
            " topic",
            "- topic",
            "provided to youtube",
            "auto generated by youtube",
            "auto-generated by youtube",
        )
    )


def source_is_self_labeled_official(server: SearchServerAdapter, item: Dict[str, Any]) -> bool:
    text = _source_text(server, item)
    return "official" in text and not source_has_authoritative_marker(server, item)


def source_popularity_score(server: SearchServerAdapter, item: Dict[str, Any]) -> float:
    for key in ("popularity", "view_count", "viewCount", "views", "play_count", "playCount"):
        value = item.get(key)
        try:
            number = float(value or 0.0)
        except (TypeError, ValueError):
            number = 0.0
        if number <= 0:
            continue
        if number <= 1.0:
            return max(0.0, min(number, 1.0))
        return min(1.0, max(0.0, (len(str(int(number))) - 3) / 7.0))
    text = _source_text(server, item)
    if "official" in text or "vevo" in text or "topic" in text:
        return 0.72
    return 0.0


def source_official_artist_score(server: SearchServerAdapter, item: Dict[str, Any]) -> float:
    text = server.normalize_text(
        " ".join(
            _text(item.get(key))
            for key in ("artist", "channel", "author", "uploader", "uploader_id")
        )
    )
    if not text:
        return 0.0
    score = 0.0
    if "vevo" in text:
        score += 1.35
    if "official" in text:
        score += 0.15 if source_is_self_labeled_official(server, item) else 0.95
    if "topic" in text:
        score += 0.9
    if any(token in text for token in ("cover", "karaoke", "tribute", "piano", "instrumental")):
        score -= 1.25
    if source_is_self_labeled_official(server, item):
        score -= 0.35
    return score


def source_artist_key(
    server: SearchServerAdapter,
    query: str,
    item: Dict[str, Any] | None,
) -> str:
    if not isinstance(item, dict):
        return ""
    normalized_query = normalize_track_title(query)
    raw_title = _text(item.get("title") or item.get("name"))
    title_parts = re.split(r"\s+[-â€“â€”]\s+", raw_title, maxsplit=1)
    if len(title_parts) == 2 and normalized_query:
        prefix = normalize_track_title(title_parts[0])
        suffix = normalize_track_title(title_parts[1])
        if prefix and (suffix == normalized_query or normalized_query in suffix):
            return prefix
    artist = server.normalize_text(
        item.get("channel")
        or item.get("artist")
        or item.get("author")
        or item.get("uploader")
        or ""
    )
    if not artist:
        return ""
    artist = re.sub(r"\b(official|topic|vevo|records|recordings|music)\b", " ", artist)
    return re.sub(r"\s+", " ", artist).strip()


def source_exact_title_diversity(
    server: SearchServerAdapter,
    query: str,
    tracks: List[Dict[str, Any]],
) -> int:
    normalized_query = normalize_track_title(query)
    artists = {
        server.normalize_text(track.get("channel") or track.get("artist") or "")
        for track in tracks or []
        if normalize_track_title(track.get("title") or "") == normalized_query
    }
    artists.discard("")
    return len(artists)


def has_trusted_exact_source(
    server: SearchServerAdapter,
    query: str,
    tracks: List[Dict[str, Any]],
) -> bool:
    normalized_query = normalize_track_title(query)
    if not normalized_query:
        return False
    for track in tracks or []:
        if normalize_track_title(track.get("title") or "") != normalized_query:
            continue
        if source_quality_score(server, track) >= 1.0:
            return True
        if source_popularity_score(server, track) >= 0.72:
            return True
    return False


def _split_artist_title(raw_title: str) -> Tuple[str, str]:
    if " - " not in raw_title:
        return "", raw_title
    left, right = raw_title.split(" - ", 1)
    left_key = normalize_artist_name(left)
    right_key = normalize_track_title(right)
    if not left_key or not right_key:
        return "", raw_title
    return left, right


def canonical_track_fields(
    item: Dict[str, Any],
    *,
    query: str = "",
) -> Tuple[str, str, str]:
    raw_title = _field_text(item, ("title", "name"))
    raw_artist = _field_text(item, ("artist", "artist_name", "channel", "author", "uploader"))
    split_artist, split_title = _split_artist_title(raw_title)
    query_key = normalize_track_title(query)
    if split_artist and split_title:
        split_title_key = normalize_track_title(split_title)
        if not query_key or query_key in split_title_key or split_title_key in query_key:
            raw_title = split_title
            raw_artist_key = normalize_artist_name(raw_artist)
            split_artist_key = normalize_artist_name(split_artist)
            if (
                not raw_artist
                or "vevo" in raw_artist.lower()
                or (split_artist_key and split_artist_key not in raw_artist_key)
            ):
                raw_artist = split_artist
    title_key = normalize_track_title(raw_title)
    artist_key = normalize_artist_name(raw_artist)
    album_key = normalize_album_title(_field_text(item, ("album", "album_title", "album_name")))
    return title_key, artist_key, album_key


def _title_match(server: SearchServerAdapter, query: str, title_key: str) -> float:
    query_key = normalize_track_title(query)
    if not query_key or not title_key:
        return 0.0
    if query_key == title_key:
        return 1.0
    if query_key in title_key or title_key in query_key:
        query_tokens = set(server.query_tokens(query))
        if len(query_tokens) <= 1 and query_key != title_key:
            return 0.62
        return 0.82
    query_tokens = set(server.query_tokens(query))
    title_tokens = set(server.query_tokens(title_key))
    if not query_tokens or not title_tokens:
        return 0.0
    return len(query_tokens & title_tokens) / max(len(query_tokens), 1)


def _entity_key(query: str, item: Dict[str, Any]) -> Tuple[str, str]:
    title_key, artist_key, _album_key = canonical_track_fields(item, query=query)
    return title_key, artist_key


def _entity_votes(
    server: SearchServerAdapter,
    query: str,
    tracks: List[Dict[str, Any]],
    memories: List[Dict[str, Any]] | None = None,
) -> Tuple[Dict[Tuple[str, str], float], Counter[Tuple[str, str]]]:
    votes: Dict[Tuple[str, str], float] = defaultdict(float)
    counts: Counter[Tuple[str, str]] = Counter()
    for index, track in enumerate(tracks):
        if not isinstance(track, dict):
            continue
        key = _entity_key(query, track)
        if not key[0]:
            continue
        title_match = _title_match(server, query, key[0])
        if title_match <= 0:
            continue
        source_quality = source_quality_score(server, track)
        popularity = max(normalized_popularity(track), _learned_popularity(track))
        vote = (
            (title_match * 4.0)
            + max(source_quality, 0.0)
            + (popularity * 0.95)
            + max(0.0, 0.75 - (index * 0.035))
        )
        votes[key] += vote
        counts[key] += 1
    for memory in memories or []:
        if memory.get("entity_type") != "track":
            continue
        title_key = _text(memory.get("title_key"))
        artist_key = _text(memory.get("artist_key"))
        if not title_key:
            continue
        confidence = float(memory.get("confidence") or 0.0)
        score = float(memory.get("score") or 0.0)
        key = (title_key, artist_key)
        votes[key] += min(6.0, 1.5 + (confidence * 2.0) + min(score, 6.0) * 0.35)
        counts[key] += max(1, int(memory.get("event_count") or 1))
    return dict(votes), counts


def _memory_boost(
    memories: List[Dict[str, Any]] | None,
    *,
    title_key: str,
    artist_key: str,
) -> float:
    best = 0.0
    for memory in memories or []:
        if memory.get("entity_type") != "track":
            continue
        if _text(memory.get("title_key")) != title_key:
            continue
        memory_artist = _text(memory.get("artist_key"))
        if memory_artist and memory_artist != artist_key:
            continue
        confidence = float(memory.get("confidence") or 0.0)
        score = float(memory.get("score") or 0.0)
        best = max(best, min(3.5, 1.0 + (confidence * 1.4) + min(score, 5.0) * 0.2))
    return best


def resolve_canonical_tracks(
    server: SearchServerAdapter,
    query: str,
    tracks: List[Dict[str, Any]],
    *,
    limit: int,
    memories: List[Dict[str, Any]] | None = None,
) -> CanonicalSearchResult:
    query_key = normalize_track_title(query)
    normalized_tracks = [dict(track) for track in tracks or [] if isinstance(track, dict)]
    votes, counts = _entity_votes(server, query, normalized_tracks, memories=memories)
    ranked_entities = sorted(votes.items(), key=lambda item: item[1], reverse=True)
    resolved_title = ""
    resolved_artist = ""
    entity_confidence = 0.0
    if ranked_entities:
        (resolved_title, resolved_artist), best_score = ranked_entities[0]
        second_score = ranked_entities[1][1] if len(ranked_entities) > 1 else 0.0
        margin = best_score - second_score
        entity_confidence = min(1.0, max(0.0, (best_score / 8.0) + (margin / 10.0)))

    def score(indexed_track: Tuple[int, Dict[str, Any]]) -> Tuple[float, float, float, float, int]:
        index, track = indexed_track
        title_key, artist_key, album_key = canonical_track_fields(track, query=query)
        entity_key = (title_key, artist_key)
        title_match = _title_match(server, query, title_key)
        raw_source_quality = source_quality_score(server, track)
        popularity = max(normalized_popularity(track), _learned_popularity(track))
        entity_score = votes.get(entity_key, 0.0)
        memory_boost = _memory_boost(memories, title_key=title_key, artist_key=artist_key)
        canonical_match = 0.0
        entity_mismatch_penalty = 0.0
        if resolved_title and title_key == resolved_title:
            canonical_match += 1.8
        if resolved_artist and artist_key == resolved_artist:
            canonical_match += 1.35
        elif (
            resolved_artist
            and resolved_title
            and title_key == resolved_title
            and artist_key
            and entity_confidence >= 0.45
        ):
            # A source can be official for itself but still be the wrong entity.
            # Do not let VEVO/Topic-style authority outrank the resolved artist
            # cluster for exact-title searches.
            entity_mismatch_penalty += 2.35 + min(max(raw_source_quality, 0.0), 1.2)
        if query_key and title_key and query_key != title_key and query_key in title_key:
            query_tokens = set(server.query_tokens(query))
            canonical_match -= 2.0 if len(query_tokens) <= 1 else 0.7
        penalty = track_result_penalty(server.raw, track, query=query)
        source_quality = raw_source_quality
        if entity_mismatch_penalty:
            source_quality = min(source_quality, 0.2)
        ranking_score = (
            (title_match * 8.5)
            + (source_quality * 1.7)
            + (popularity * 1.35)
            + (entity_score * 0.22)
            + memory_boost
            + canonical_match
            - penalty
            - entity_mismatch_penalty
            - (index * 0.01)
        )
        track["canonical_track_title_key"] = title_key
        track["canonical_artist_key"] = artist_key
        track["canonical_album_key"] = album_key
        track["canonical_entity_confidence"] = round(entity_confidence, 4)
        track["source_quality_score"] = round(source_quality, 4)
        track["ranking_features"] = {
            **dict(track.get("ranking_features") or {}),
            "canonical_title_match": round(title_match, 4),
            "canonical_entity_vote": round(entity_score, 4),
            "canonical_match": round(canonical_match, 4),
            "canonical_entity_mismatch_penalty": round(entity_mismatch_penalty, 4),
            "query_memory_boost": round(memory_boost, 4),
            "source_quality": round(source_quality, 4),
            "raw_source_quality": round(raw_source_quality, 4),
            "quality_penalty": round(penalty, 4),
        }
        return (
            ranking_score,
            source_quality,
            popularity,
            counts.get(entity_key, 0),
            -index,
        )

    ranked_tracks = [
        track
        for _index, track in sorted(
            enumerate(normalized_tracks),
            key=score,
            reverse=True,
        )
    ]
    top_quality = source_quality_score(server, ranked_tracks[0]) if ranked_tracks else 0.0
    diagnostics = CanonicalSearchDiagnostics(
        query_key=query_key,
        resolved_title=resolved_title,
        resolved_artist=resolved_artist,
        entity_confidence=entity_confidence,
        entity_vote_count=counts.get((resolved_title, resolved_artist), 0),
        entity_candidate_count=len(ranked_entities),
        top_source_quality=top_quality,
    )
    return CanonicalSearchResult(
        tracks=ranked_tracks[: max(limit, 1)],
        diagnostics=diagnostics,
    )
