from __future__ import annotations

import re
import unicodedata
import math
from typing import Any, Dict, Iterable, List, Sequence

from ..storage.postgres import upsert_catalog_rows


_WHITESPACE_RE = re.compile(r"\s+")
_SEPARATOR_RE = re.compile(r"[\|_/]+")
_PUNCT_RE = re.compile(r"[^\w\s]")
_BRACKET_RE = re.compile(r"(\[[^\]]*\]|\([^\)]*\)|\{[^\}]*\})")
_NOISE_TOKEN_RE = re.compile(
    r"\b("
    r"acoustic|bonus|clean|deluxe|demo|edit|explicit|instrumental|karaoke|live|lyric|mix|mono|official|"
    r"radio|remaster|remastered|session|single|slowed|soundtrack|sped|stereo|topic|tribute|version|video"
    r")\b",
    re.IGNORECASE,
)
_FEAT_RE = re.compile(r"\s+(feat|featuring|ft)\.?\s+.*$", re.IGNORECASE)
_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
_COMPACT_DATE_RE = re.compile(r"^(19|20)\d{6}$")
_COMPACT_NUMBER_RE = re.compile(
    r"^\s*([+-]?\d[\d,]*(?:\.\d+)?)\s*([kmbt]?)",
    re.IGNORECASE,
)
_YOUTUBE_VIDEO_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")
_YOUTUBE_THUMBNAIL_ID_RE = re.compile(r"/vi/([^/]+)/", re.IGNORECASE)
_UNOFFICIAL_SOURCE_RE = re.compile(
    r"\b(tribute|karaoke|soundalike|lounge|juke[- ]?box|fitness mix|"
    r"workout mix|background music|coffee shop music|relaxing piano|"
    r"cover band|revival|various artists|nature sounds|meditation music|"
    r"sleep music|instrumental cover|acoustic cover|chillout compilation|"
    r"relaxing guitar|guitar relaxing|calm oasis|mellow mates|chill flow radio|"
    r"restaurant background|cafe music|study music|healing music|spa music)\b",
    re.IGNORECASE,
)
_OFFICIAL_SOURCE_RE = re.compile(
    r"\b(official|vevo|provided to youtube|auto-generated by youtube|topic)\b",
    re.IGNORECASE,
)
_KIDS_AUDIENCE_RE = re.compile(
    r"\b("
    r"baby|babies|baby shark|children|children's|childrens|kids|kid song|kids song|"
    r"nursery|nursery rhyme|preschool|kindergarten|toddler|toddlers|cartoon|"
    r"cocomelon|pinkfong|kiboomers|super simple songs|little angel|chu chu tv|"
    r"mother goose|educational songs|learning songs"
    r")\b",
    re.IGNORECASE,
)
_FAMILY_AUDIENCE_RE = re.compile(
    r"\b(disney junior|nick jr|pbs kids|sesame street|barney|paw patrol|peppa pig)\b",
    re.IGNORECASE,
)

_GENRE_ALIAS_RULES: Sequence[tuple[str, str, tuple[str, ...]]] = (
    ("rock", "classic_rock", ("classic rock", "rock and roll", "rock n roll", "rock n' roll", "70s rock", "80s rock")),
    ("rock", "hard_rock", ("hard rock", "arena rock", "glam rock", "blues rock", "southern rock")),
    ("rock", "alternative_rock", ("alternative rock", "alt rock", "indie rock", "post rock", "post-rock")),
    ("rock", "progressive_rock", ("progressive rock", "prog rock", "psychedelic rock")),
    ("metal", "heavy_metal", ("metal", "heavy metal", "thrash metal", "doom metal", "power metal", "black metal")),
    ("punk", "punk", ("punk", "pop punk", "post punk", "post-punk")),
    ("latin", "latin_pop", ("latin", "reggaeton", "bachata", "salsa", "corridos", "latin pop")),
    ("pop", "pop", ("pop", "dance pop", "synth pop", "synth-pop", "electropop", "teen pop")),
    ("rnb", "soul", ("rnb", "r and b", "r&b", "soul", "neo soul", "neo-soul")),
    ("funk", "funk", ("funk", "disco", "groove")),
    ("hip_hop", "rap", ("hip hop", "hip-hop", "rap", "trap", "drill")),
    ("electronic", "edm", ("edm", "electronic", "house", "techno", "trance", "dubstep", "drum and bass", "dnb")),
    ("electronic", "ambient", ("ambient", "downtempo", "chillout", "lofi", "lo-fi", "lo fi")),
    ("jazz", "jazz", ("jazz", "bebop", "swing", "modal jazz", "cool jazz", "vocal jazz", "smooth jazz")),
    ("blues", "blues", ("blues", "delta blues", "electric blues", "chicago blues")),
    ("country", "country", ("country", "nashville", "americana", "bluegrass", "honky tonk")),
    ("folk", "folk", ("folk", "singer songwriter", "singer-songwriter", "acoustic folk")),
    ("soundtrack", "soundtrack", ("soundtrack", "score", "ost", "original score", "motion picture")),
    ("devotional", "devotional", ("devotional", "gospel", "worship", "bhajan", "qawwali", "nasheed")),
)

_MOOD_TRAIT_RULES: Sequence[tuple[str, tuple[str, ...], Dict[str, float]]] = (
    ("workout", ("workout", "gym", "fitness", "pump", "hype", "anthem", "high energy"), {"energy": 0.82, "drive": 0.82}),
    ("rock_drive", ("hard rock", "metal", "punk", "thrash", "arena rock"), {"energy": 0.78, "drive": 0.76}),
    ("dance", ("dance", "edm", "house", "club", "disco", "funk", "groove"), {"energy": 0.72, "danceability": 0.78}),
    ("chill", ("chill", "mellow", "soft", "downtempo", "lofi", "lo-fi", "acoustic"), {"calmness": 0.72, "softness": 0.7}),
    ("focus", ("ambient", "study", "focus", "piano", "instrumental", "score", "soundtrack"), {"calmness": 0.76, "instrumentalness": 0.72}),
    ("dark", ("dark", "goth", "doom", "melancholy", "sad"), {"darkness": 0.72}),
)

_LANGUAGE_ALIASES = {
    "en": "english",
    "eng": "english",
    "english": "english",
    "es": "spanish",
    "esp": "spanish",
    "espanol": "spanish",
    "español": "spanish",
    "spanish": "spanish",
    "pt": "portuguese",
    "por": "portuguese",
    "portuguese": "portuguese",
    "vi": "vietnamese",
    "vie": "vietnamese",
    "vietnamese": "vietnamese",
    "ja": "japanese",
    "japanese": "japanese",
    "ko": "korean",
    "korean": "korean",
    "zh": "chinese",
    "chinese": "chinese",
    "hi": "hindi",
    "hindi": "hindi",
}

_REGION_ALIASES = {
    "usa": "us",
    "united states": "us",
    "united states of america": "us",
    "america": "us",
    "uk": "gb",
    "united kingdom": "gb",
    "england": "gb",
    "viet nam": "vietnam",
    "việt nam": "vietnam",
    "latin america": "latin_america",
    "latam": "latin_america",
    "east asia": "east_asia",
    "south korea": "korea",
}


def _text(value: Any) -> str:
    return str(value or "").strip()


def _display_text(*values: Any) -> str:
    for value in values:
        text = _text(value)
        if text:
            return text
    return ""


def parse_compact_number(value: Any, default: float = 0.0) -> float:
    if isinstance(value, (int, float)):
        return float(value)
    match = _COMPACT_NUMBER_RE.match(str(value or "").replace("\u00a0", " "))
    if match is None:
        return default
    try:
        number = float(match.group(1).replace(",", ""))
    except (TypeError, ValueError):
        return default
    multiplier = {
        "k": 1_000.0,
        "m": 1_000_000.0,
        "b": 1_000_000_000.0,
        "t": 1_000_000_000_000.0,
    }.get(match.group(2).lower(), 1.0)
    return number * multiplier


def _number(value: Any, default: float = 0.0) -> float:
    return parse_compact_number(value, default)


def normalize_catalog_text(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value)).lower()
    text = text.replace("&", " and ")
    text = _SEPARATOR_RE.sub(" ", text)
    text = _PUNCT_RE.sub(" ", text)
    text = _WHITESPACE_RE.sub(" ", text).strip()
    return text


def normalize_catalog_language(value: Any) -> str:
    text = normalize_catalog_text(value)
    return _LANGUAGE_ALIASES.get(text, text or "unknown")


def normalize_catalog_region(value: Any) -> str:
    text = normalize_catalog_text(value).replace(" ", "_")
    return _REGION_ALIASES.get(text.replace("_", " "), _REGION_ALIASES.get(text, text or "unknown"))


def _append_unique(output: List[str], value: Any) -> None:
    normalized = normalize_catalog_text(value).replace(" ", "_")
    if normalized and normalized not in output:
        output.append(normalized)


def normalized_genre_metadata(item: Dict[str, Any]) -> Dict[str, Any]:
    values: List[Any] = []
    for key in ("genre", "subgenre", "style", "category", "mood"):
        values.append(item.get(key))
    for key in ("genres", "styles", "tags", "discovery_genres", "track_type_tags"):
        raw = item.get(key)
        if isinstance(raw, dict):
            values.extend(raw.values())
        elif isinstance(raw, (list, tuple, set)):
            values.extend(raw)
        else:
            values.append(raw)

    text = catalog_metadata_text(item)
    genres: List[str] = []
    subgenres: List[str] = []
    for value in values:
        if isinstance(value, str):
            _append_unique(genres, value)
    for primary, secondary, aliases in _GENRE_ALIAS_RULES:
        if any(alias in text for alias in aliases):
            _append_unique(genres, primary)
            _append_unique(subgenres, secondary)
    if not genres and subgenres:
        genres.append(subgenres[0])
    primary_genre = genres[0] if genres else ""
    subgenre = subgenres[0] if subgenres else ""
    discovery_genres = list(dict.fromkeys([*genres, *subgenres]))
    return {
        "genre": primary_genre,
        "subgenre": subgenre,
        "genres": genres,
        "discovery_genres": discovery_genres,
    }


def inferred_language_region(item: Dict[str, Any]) -> Dict[str, Any]:
    language = normalize_catalog_language(item.get("language"))
    region = normalize_catalog_region(item.get("region"))
    language_confidence = _number(item.get("language_confidence"), 0.0)
    region_confidence = _number(item.get("region_confidence"), 0.0)
    language_source = _text(item.get("language_source"))
    region_source = _text(item.get("region_source"))
    text = catalog_metadata_text(item)
    if language != "unknown" and region != "unknown":
        return {
            "language": language,
            "region": region,
            "language_confidence": round(language_confidence or 0.9, 4),
            "region_confidence": round(region_confidence or 0.86, 4),
            "language_source": language_source or "source_metadata",
            "region_source": region_source or "source_metadata",
        }
    for inferred_language, inferred_region, pattern in (
        (item[0], item[1], item[2])
        for item in (
            ("spanish", "latin_america", re.compile(r"\b(en espanol|espanol|latin|reggaeton|bachata|salsa)\b", re.IGNORECASE)),
            ("portuguese", "brazil", re.compile(r"\b(brasil|brazil|sertanejo|mpb|portuguese)\b", re.IGNORECASE)),
            ("french", "francophone", re.compile(r"\b(french|francais|chanson|paris)\b", re.IGNORECASE)),
            ("vietnamese", "vietnam", re.compile(r"\b(vietnam|vietnamese|vpop|v-pop)\b", re.IGNORECASE)),
            ("korean", "korea", re.compile(r"\b(korean|kpop|k-pop)\b", re.IGNORECASE)),
            ("japanese", "japan", re.compile(r"\b(japanese|jpop|j-pop|anime)\b", re.IGNORECASE)),
            ("hindi", "india", re.compile(r"\b(hindi|bollywood|punjabi|tamil|telugu|bhojpuri)\b", re.IGNORECASE)),
        )
    ):
        if pattern.search(text):
            if language == "unknown":
                language = inferred_language
                language_confidence = language_confidence or 0.78
                language_source = language_source or "text_hint"
            if region == "unknown":
                region = inferred_region
                region_confidence = region_confidence or 0.74
                region_source = region_source or "text_hint"
            break
    return {
        "language": language,
        "region": region,
        "language_confidence": round(language_confidence if language != "unknown" else 0.0, 4),
        "region_confidence": round(region_confidence if region != "unknown" else 0.0, 4),
        "language_source": language_source or ("unknown" if language == "unknown" else "derived_metadata"),
        "region_source": region_source or ("unknown" if region == "unknown" else "derived_metadata"),
    }


def _strip_bracketed_noise(value: str) -> str:
    def _replace(match: re.Match[str]) -> str:
        content = normalize_catalog_text(match.group(0))
        return " " if _NOISE_TOKEN_RE.search(content) else match.group(0)

    return _BRACKET_RE.sub(_replace, value)


def _strip_suffix_noise(value: str) -> str:
    parts = re.split(r"\s+-\s+", value)
    if len(parts) <= 1:
        return value
    kept: List[str] = [parts[0]]
    for part in parts[1:]:
        if _NOISE_TOKEN_RE.search(normalize_catalog_text(part)):
            continue
        kept.append(part)
    return " - ".join(kept)


def normalize_artist_name(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = re.sub(r"\s*-\s*topic$", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*vevo$", "", text, flags=re.IGNORECASE)
    text = _FEAT_RE.sub("", text)
    return normalize_catalog_text(text)


def normalize_track_title(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = _strip_bracketed_noise(text)
    text = _strip_suffix_noise(text)
    return normalize_catalog_text(text)


def normalize_album_title(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = _strip_bracketed_noise(text)
    text = _strip_suffix_noise(text)
    return normalize_catalog_text(text)


def canonical_artist_identity(artist: Dict[str, Any] | str) -> str:
    if isinstance(artist, dict):
        artist_id = _text(artist.get("id"))
        if artist_id:
            return artist_id
        return normalize_artist_name(artist.get("name") or artist.get("artist") or artist.get("channel"))
    return normalize_artist_name(artist)


def canonical_artist_record_key(artist: Dict[str, Any] | str) -> str:
    """Stable artist identity independent from a temporary provider browse id."""
    if not isinstance(artist, dict):
        normalized_name = normalize_artist_name(artist)
        return f"artist-name:{normalized_name}" if normalized_name else ""
    musicbrainz_id = _text(
        artist.get("musicbrainz_artist_id")
        or artist.get("artist_mbid")
        or artist.get("mb_artist_id")
    )
    if musicbrainz_id:
        return f"musicbrainz:artist:{musicbrainz_id.casefold()}"
    existing = _text(
        artist.get("canonical_artist_id")
        or artist.get("canonical_artist_key")
    )
    if existing.startswith(("musicbrainz:artist:", "artist-name:")):
        return existing
    normalized_name = normalize_artist_name(
        artist.get("name")
        or artist.get("artist")
        or artist.get("artist_name")
        or artist.get("channel")
    )
    return f"artist-name:{normalized_name}" if normalized_name else ""


def canonical_album_identity(album: Dict[str, Any]) -> str:
    album_id = _text(album.get("id") or album.get("album_id") or album.get("albumId"))
    if album_id:
        return album_id
    title_key = normalize_album_title(album.get("title") or album.get("album"))
    artist_key = normalize_artist_name(
        album.get("artist") or album.get("channel") or album.get("artist_name")
    )
    if title_key and artist_key:
        return f"{title_key}|{artist_key}"
    return title_key or artist_key


def canonical_title_artist_identity(track: Dict[str, Any]) -> str:
    title_key = normalize_track_title(track.get("title") or track.get("name"))
    artist_key = normalize_artist_name(
        track.get("channel") or track.get("artist") or track.get("author") or track.get("artist_name")
    )
    if title_key and artist_key:
        return f"{title_key}|{artist_key}"
    return title_key or artist_key


def verified_playback_source(item: Dict[str, Any]) -> Dict[str, str]:
    """Return explicit playback evidence without treating metadata IDs as media."""
    if not isinstance(item, dict) or item.get("playable") is False:
        return {}
    playback = item.get("playback")
    playback = playback if isinstance(playback, dict) else {}
    provider = normalize_catalog_text(
        playback.get("provider")
        or item.get("playback_provider")
        or item.get("source_provider")
        or item.get("provider")
    )
    provider = {
        "youtube music": "youtube",
        "youtube_music": "youtube",
        "ytmusic": "youtube",
    }.get(provider, provider)
    source_id = _text(
        playback.get("source_id")
        or playback.get("video_id")
        or item.get("playback_source_id")
    )
    if provider == "youtube" and _YOUTUBE_VIDEO_ID_RE.fullmatch(source_id):
        return {"provider": "youtube", "source_id": source_id}
    if provider == "audius" and source_id:
        return {"provider": "audius", "source_id": source_id.removeprefix("audius:")}

    # `videoId` is provider-scoped. A generic `id` may instead be a
    # MusicBrainz identity, album browse ID, canonical key, or text slug.
    video_id = _text(item.get("videoId") or item.get("video_id"))
    if _YOUTUBE_VIDEO_ID_RE.fullmatch(video_id):
        return {"provider": "youtube", "source_id": video_id}
    return {}


def catalog_thumbnail_url(
    item: Dict[str, Any],
    *,
    entity_type: str,
) -> str:
    """Read entity artwork without treating every entity ID as a video ID."""
    if not isinstance(item, dict):
        return ""
    for key in (
        "thumbnail",
        "artwork_url",
        "artwork",
        "cover_url",
        "cover",
        "image_url",
        "image",
    ):
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            url = value.strip()
            youtube_match = _YOUTUBE_THUMBNAIL_ID_RE.search(url)
            if youtube_match:
                source = verified_playback_source(item)
                if (
                    not _YOUTUBE_VIDEO_ID_RE.fullmatch(youtube_match.group(1))
                    or source.get("provider") != "youtube"
                    or source.get("source_id") != youtube_match.group(1)
                ):
                    continue
            return url
        if isinstance(value, dict):
            url = _text(value.get("url") or value.get("src"))
            if url:
                return url
    thumbnails = item.get("thumbnails") or item.get("images")
    if isinstance(thumbnails, list):
        for raw in reversed(thumbnails):
            if isinstance(raw, str) and raw.strip():
                return raw.strip()
            if isinstance(raw, dict):
                url = _text(raw.get("url") or raw.get("src"))
                if url:
                    return url

    if str(entity_type or "").strip().lower() != "track":
        return ""
    source = verified_playback_source(item)
    if source.get("provider") == "youtube":
        return f"https://i.ytimg.com/vi/{source['source_id']}/hqdefault.jpg"
    return ""


def canonical_track_identity(track: Dict[str, Any]) -> str:
    track_id = _text(track.get("id"))
    if track_id:
        return track_id
    return canonical_title_artist_identity(track)


def catalog_metadata_text(item: Dict[str, Any]) -> str:
    values: List[str] = []
    for key in (
        "title",
        "name",
        "artist",
        "artist_name",
        "channel",
        "author",
        "album",
        "album_title",
        "description",
        "source_name",
        "provider",
    ):
        value = item.get(key)
        if isinstance(value, dict):
            values.extend(str(entry or "") for entry in value.values())
        elif isinstance(value, (list, tuple, set)):
            values.extend(str(entry or "") for entry in value)
        else:
            values.append(str(value or ""))
    return normalize_catalog_text(" ".join(values))


def is_unofficial_catalog_item(item: Dict[str, Any]) -> bool:
    explicit = normalize_catalog_text(item.get("source_authority")).replace(" ", "_")
    if explicit == "search_only":
        return True
    if explicit in {"official", "canonical", "verified_catalog"}:
        return False
    text = catalog_metadata_text(item)
    return bool(_UNOFFICIAL_SOURCE_RE.search(text))


def catalog_source_authority(item: Dict[str, Any]) -> str:
    explicit = normalize_catalog_text(item.get("source_authority")).replace(" ", "_")
    if explicit in {
        "search_only",
        "official",
        "canonical",
        "verified_catalog",
    }:
        return explicit
    text = catalog_metadata_text(item)
    if is_unofficial_catalog_item(item):
        return "search_only"
    if _OFFICIAL_SOURCE_RE.search(text):
        return "official"
    if _text(item.get("album_id") or item.get("browseId") or item.get("artist_id")):
        return "canonical"
    if (
        _text(item.get("id"))
        and normalize_artist_name(
            item.get("artist") or item.get("artist_name") or item.get("channel")
        )
        and normalize_track_title(item.get("title") or item.get("name"))
        and normalize_catalog_text(
            item.get("provider") or item.get("source_name") or item.get("source")
        )
        in {"youtube music", "ytmusic", "artist catalog", "artist discography"}
    ):
        return "verified_catalog"
    return "unknown"


def canonical_source_identity(item: Dict[str, Any], *, entity_type: str) -> str:
    provider = normalize_catalog_text(
        item.get("provider") or item.get("source_name") or item.get("source") or "catalog"
    )
    if entity_type == "album":
        identity = canonical_album_identity(item)
    elif entity_type == "artist":
        identity = canonical_artist_identity(item)
    else:
        identity = canonical_track_identity(item)
    return f"{provider}:{identity}" if provider and identity else identity


def normalized_release_metadata(item: Dict[str, Any]) -> Dict[str, Any]:
    release_date = _display_text(
        item.get("release_date"),
        item.get("releaseDate"),
        item.get("date"),
        item.get("published_at"),
        item.get("publishedAt"),
        item.get("published"),
        item.get("upload_date"),
        item.get("uploadDate"),
        item.get("year"),
        item.get("release_year"),
    )
    if _COMPACT_DATE_RE.match(release_date):
        release_date = f"{release_date[:4]}-{release_date[4:6]}-{release_date[6:8]}"
    match = _YEAR_RE.search(release_date)
    return {
        "release_date": release_date,
        "release_year": int(match.group(0)) if match else None,
    }


def normalized_popularity(item: Dict[str, Any]) -> float:
    explicit = item.get("popularity")
    if explicit not in (None, ""):
        value = _number(explicit, 0.0)
        if value > 1.0:
            value = value / 100.0
        return round(max(0.0, min(value, 1.0)), 4)
    for key in (
        "view_count",
        "viewCount",
        "views",
        "play_count",
        "playCount",
        "plays",
        "subscriber_count",
        "subscriberCount",
        "subscribers",
    ):
        value = _number(item.get(key), 0.0)
        if value > 0:
            # Log scaling keeps viral tracks from flattening every other item.
            return round(max(0.0, min(math.log10(value + 1.0) / 9.0, 1.0)), 4)
    return 0.0


def catalog_artist_graph_keys(item: Dict[str, Any]) -> List[str]:
    values: List[Any] = []
    for key in ("artist", "artist_name", "channel", "author", "name"):
        values.append(item.get(key))
    artists = item.get("artists")
    if isinstance(artists, list):
        for artist in artists:
            if isinstance(artist, dict):
                values.append(artist.get("name") or artist.get("title") or artist.get("artist"))
            else:
                values.append(artist)
    for key in ("related_artists", "similar_artists", "collaborators", "featured_artists"):
        extra = item.get(key)
        if isinstance(extra, dict):
            values.extend(extra.values())
        elif isinstance(extra, (list, tuple, set)):
            values.extend(extra)
        else:
            values.append(extra)
    output: List[str] = []
    seen = set()
    for value in values:
        normalized = normalize_artist_name(value)
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        output.append(normalized)
    return output


def normalized_audio_traits(item: Dict[str, Any]) -> Dict[str, float]:
    axes = item.get("audio_traits") or item.get("mood_axes") or {}
    axes = axes if isinstance(axes, dict) else {}
    output: Dict[str, float] = {}
    for key in ("energy", "drive", "calmness", "softness", "darkness", "danceability", "valence"):
        raw = axes.get(key, item.get(key))
        if raw in (None, ""):
            continue
        output[key] = round(max(0.0, min(_number(raw), 1.0)), 4)
    if output:
        return output
    text = catalog_metadata_text(item)
    for _name, aliases, traits in _MOOD_TRAIT_RULES:
        if any(alias in text for alias in aliases):
            for key, value in traits.items():
                output[key] = max(output.get(key, 0.0), value)
    if output.get("calmness", 0.0) >= 0.7:
        output.setdefault("energy", 0.32)
    return output


def normalized_audience_metadata(item: Dict[str, Any]) -> Dict[str, Any]:
    explicit = normalize_catalog_text(
        item.get("audience_profile")
        or item.get("audience")
        or item.get("content_audience")
    ).replace(" ", "_")
    explicit_confidence = _number(
        item.get("audience_confidence")
        or item.get("content_audience_confidence"),
        0.0,
    )
    if explicit and explicit not in {"unknown", "general"}:
        return {
            "audience_profile": explicit,
            "audience_confidence": round(explicit_confidence or 0.9, 4),
            "audience_source": _text(item.get("audience_source")) or "source_metadata",
        }

    text = catalog_metadata_text(item)
    if _KIDS_AUDIENCE_RE.search(text):
        return {
            "audience_profile": "kids_family",
            "audience_confidence": 0.92,
            "audience_source": "text_hint",
        }
    if _FAMILY_AUDIENCE_RE.search(text):
        return {
            "audience_profile": "kids_family",
            "audience_confidence": 0.84,
            "audience_source": "text_hint",
        }
    return {
        "audience_profile": "general",
        "audience_confidence": round(explicit_confidence or 0.55, 4),
        "audience_source": _text(item.get("audience_source")) or "default_general",
    }


def _shared_catalog_metadata(item: Dict[str, Any], *, entity_type: str) -> Dict[str, Any]:
    release = normalized_release_metadata(item)
    popularity = normalized_popularity(item)
    language_region = inferred_language_region(item)
    genres = normalized_genre_metadata(item)
    audience = normalized_audience_metadata(item)
    return {
        **release,
        **genres,
        **language_region,
        **audience,
        "popularity": popularity,
        "audio_traits": normalized_audio_traits(item),
        "artist_graph_keys": catalog_artist_graph_keys(item),
        "source_authority": catalog_source_authority(item),
        "canonical_source_identity": canonical_source_identity(
            item,
            entity_type=entity_type,
        ),
    }


def normalized_track_payload(track: Dict[str, Any]) -> Dict[str, Any]:
    artist_name = _display_text(track.get("channel"), track.get("artist"), track.get("author"))
    album_title = _display_text(track.get("album"))
    payload = dict(track)
    payload.update(
        {
            "artist_name": artist_name,
            "album_title": album_title,
            "normalized_title": normalize_track_title(track.get("title") or track.get("name")),
            "normalized_artist_name": normalize_artist_name(artist_name),
            "normalized_album_title": normalize_album_title(album_title),
            "canonical_track_identity": canonical_track_identity(track),
            "canonical_title_artist_identity": canonical_title_artist_identity(track),
            **_shared_catalog_metadata(track, entity_type="track"),
        }
    )
    playback = verified_playback_source(payload)
    if playback:
        payload["playback"] = {
            **(
                dict(payload.get("playback"))
                if isinstance(payload.get("playback"), dict)
                else {}
            ),
            **playback,
        }
        payload["playback_provider"] = playback["provider"]
        payload["playback_source_id"] = playback["source_id"]
        if playback["provider"] == "youtube":
            payload["videoId"] = playback["source_id"]
    thumbnail = catalog_thumbnail_url(payload, entity_type="track")
    if thumbnail:
        payload["thumbnail"] = thumbnail
    else:
        payload.pop("thumbnail", None)
    return payload


def normalized_artist_payload(artist: Dict[str, Any]) -> Dict[str, Any]:
    name = _display_text(artist.get("name"), artist.get("artist"), artist.get("channel"))
    normalized_name = normalize_artist_name(name)
    aliases: List[str] = []
    for value in (
        name,
        artist.get("artist"),
        artist.get("artist_name"),
        artist.get("channel"),
        *(artist.get("aliases") or [] if isinstance(artist.get("aliases"), list) else []),
    ):
        alias = normalize_artist_name(value)
        if alias and alias not in aliases:
            aliases.append(alias)
    payload = dict(artist)
    payload.update(
        {
            "name": name,
            "normalized_name": normalized_name,
            "canonical_artist_identity": canonical_artist_identity(artist),
            "canonical_artist_id": canonical_artist_record_key(artist),
            "provider_artist_id": _text(artist.get("id")),
            "artist_aliases": aliases,
            **_shared_catalog_metadata(artist, entity_type="artist"),
        }
    )
    thumbnail = catalog_thumbnail_url(payload, entity_type="artist")
    if thumbnail:
        payload["thumbnail"] = thumbnail
    else:
        payload.pop("thumbnail", None)
    return payload


def normalized_album_payload(album: Dict[str, Any]) -> Dict[str, Any]:
    title = _display_text(album.get("title"), album.get("album"))
    artist_name = _display_text(album.get("artist"), album.get("channel"), album.get("artist_name"))
    payload = dict(album)
    payload.update(
        {
            "title": title,
            "artist_name": artist_name,
            "normalized_title": normalize_album_title(title),
            "normalized_artist_name": normalize_artist_name(artist_name),
            "canonical_album_identity": canonical_album_identity(album),
            **_shared_catalog_metadata(album, entity_type="album"),
        }
    )
    thumbnail = catalog_thumbnail_url(payload, entity_type="album")
    if thumbnail:
        payload["thumbnail"] = thumbnail
    else:
        payload.pop("thumbnail", None)
    return payload


def _dedupe_rows(rows: Sequence[Dict[str, Any]], key_name: str) -> List[Dict[str, Any]]:
    deduped: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        key = _text(row.get(key_name))
        if not key:
            continue
        deduped[key] = dict(row)
    return list(deduped.values())


def cache_tracks(tracks: Iterable[Dict]) -> None:
    rows = []
    for track in tracks or []:
        if not isinstance(track, dict):
            continue
        track_id = _text(track.get("id"))
        if not track_id:
            continue
        normalized = normalized_track_payload(track)
        if not _text(normalized.get("thumbnail")):
            normalized.pop("thumbnail", None)
        rows.append(
            {
                "track_id": track_id,
                "title": _display_text(track.get("title"), track.get("name")),
                "artist_name": normalized.get("artist_name") or "",
                "album_title": normalized.get("album_title") or "",
                **normalized,
            }
        )
    upsert_catalog_rows(
        table="catalog_tracks",
        key_name="track_id",
        rows=_dedupe_rows(rows, "track_id"),
    )


def cache_artists(artists: Iterable[Dict]) -> None:
    rows = []
    for artist in artists or []:
        if not isinstance(artist, dict):
            continue
        artist_id = _text(artist.get("id"))
        if not artist_id:
            continue
        normalized = normalized_artist_payload(artist)
        if not _text(normalized.get("thumbnail")):
            normalized.pop("thumbnail", None)
        rows.append({"artist_id": artist_id, **normalized})
    upsert_catalog_rows(
        table="catalog_artists",
        key_name="artist_id",
        rows=_dedupe_rows(rows, "artist_id"),
    )


def cache_albums(albums: Iterable[Dict]) -> None:
    rows = []
    for album in albums or []:
        if not isinstance(album, dict):
            continue
        album_id = _text(album.get("id"))
        if not album_id:
            continue
        normalized = normalized_album_payload(album)
        if not _text(normalized.get("thumbnail")):
            normalized.pop("thumbnail", None)
        rows.append({"album_id": album_id, **normalized})
    upsert_catalog_rows(
        table="catalog_albums",
        key_name="album_id",
        rows=_dedupe_rows(rows, "album_id"),
    )


def cache_search_payload(
    *,
    tracks: List[Dict],
    artists: List[Dict],
    albums: List[Dict],
) -> None:
    cache_tracks(tracks)
    cache_artists(artists)
    cache_albums(albums)
