from __future__ import annotations

import re
import unicodedata
import math
from typing import Any, Dict, Iterable, List, Sequence

from ..storage.postgres import upsert_catalog_rows


_WHITESPACE_RE = re.compile(r"\s+")
_SEPARATOR_RE = re.compile(r"[\|_/]+")
_PUNCT_RE = re.compile(r"[^\w\s]")
_BRACKET_RE = re.compile(r"(\[[^\]]*\]|\([^\)]*\)|\{[^\}]*\})")
_NOISE_TOKEN_RE = re.compile(
    r"\b("
    r"acoustic|bonus|clean|deluxe|demo|edit|explicit|instrumental|karaoke|live|lyric|mix|mono|official|"
    r"radio|remaster|remastered|session|single|slowed|soundtrack|sped|stereo|topic|tribute|version|video"
    r")\b",
    re.IGNORECASE,
)
_FEAT_RE = re.compile(r"\s+(feat|featuring|ft)\.?\s+.*$", re.IGNORECASE)
_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
_COMPACT_DATE_RE = re.compile(r"^(19|20)\d{6}$")
_UNOFFICIAL_SOURCE_RE = re.compile(
    r"\b(tribute|karaoke|soundalike|lounge|juke[- ]?box|fitness mix|"
    r"workout mix|background music|coffee shop music|relaxing piano|"
    r"cover band|revival|various artists|nature sounds|meditation music|"
    r"sleep music|instrumental cover|acoustic cover|chillout compilation|"
    r"relaxing guitar|guitar relaxing|calm oasis|mellow mates|chill flow radio|"
    r"restaurant background|cafe music|study music|healing music|spa music)\b",
    re.IGNORECASE,
)
_OFFICIAL_SOURCE_RE = re.compile(
    r"\b(official|vevo|provided to youtube|auto-generated by youtube|topic)\b",
    re.IGNORECASE,
)

_LANGUAGE_ALIASES = {
    "en": "english",
    "eng": "english",
    "english": "english",
    "es": "spanish",
    "esp": "spanish",
    "espanol": "spanish",
    "español": "spanish",
    "spanish": "spanish",
    "pt": "portuguese",
    "por": "portuguese",
    "portuguese": "portuguese",
    "vi": "vietnamese",
    "vie": "vietnamese",
    "vietnamese": "vietnamese",
    "ja": "japanese",
    "japanese": "japanese",
    "ko": "korean",
    "korean": "korean",
    "zh": "chinese",
    "chinese": "chinese",
    "hi": "hindi",
    "hindi": "hindi",
}

_REGION_ALIASES = {
    "usa": "us",
    "united states": "us",
    "united states of america": "us",
    "america": "us",
    "uk": "gb",
    "united kingdom": "gb",
    "england": "gb",
    "viet nam": "vietnam",
    "việt nam": "vietnam",
    "latin america": "latin_america",
    "latam": "latin_america",
    "east asia": "east_asia",
    "south korea": "korea",
}


def _text(value: Any) -> str:
    return str(value or "").strip()


def _display_text(*values: Any) -> str:
    for value in values:
        text = _text(value)
        if text:
            return text
    return ""


def _number(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def normalize_catalog_text(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value)).lower()
    text = text.replace("&", " and ")
    text = _SEPARATOR_RE.sub(" ", text)
    text = _PUNCT_RE.sub(" ", text)
    text = _WHITESPACE_RE.sub(" ", text).strip()
    return text


def normalize_catalog_language(value: Any) -> str:
    text = normalize_catalog_text(value)
    return _LANGUAGE_ALIASES.get(text, text or "unknown")


def normalize_catalog_region(value: Any) -> str:
    text = normalize_catalog_text(value).replace(" ", "_")
    return _REGION_ALIASES.get(text.replace("_", " "), _REGION_ALIASES.get(text, text or "unknown"))


def _strip_bracketed_noise(value: str) -> str:
    def _replace(match: re.Match[str]) -> str:
        content = normalize_catalog_text(match.group(0))
        return " " if _NOISE_TOKEN_RE.search(content) else match.group(0)

    return _BRACKET_RE.sub(_replace, value)


def _strip_suffix_noise(value: str) -> str:
    parts = re.split(r"\s+-\s+", value)
    if len(parts) <= 1:
        return value
    kept: List[str] = [parts[0]]
    for part in parts[1:]:
        if _NOISE_TOKEN_RE.search(normalize_catalog_text(part)):
            continue
        kept.append(part)
    return " - ".join(kept)


def normalize_artist_name(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = re.sub(r"\s*-\s*topic$", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*vevo$", "", text, flags=re.IGNORECASE)
    text = _FEAT_RE.sub("", text)
    return normalize_catalog_text(text)


def normalize_track_title(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = _strip_bracketed_noise(text)
    text = _strip_suffix_noise(text)
    return normalize_catalog_text(text)


def normalize_album_title(value: Any) -> str:
    text = unicodedata.normalize("NFKC", _text(value))
    text = _strip_bracketed_noise(text)
    text = _strip_suffix_noise(text)
    return normalize_catalog_text(text)


def canonical_artist_identity(artist: Dict[str, Any] | str) -> str:
    if isinstance(artist, dict):
        artist_id = _text(artist.get("id"))
        if artist_id:
            return artist_id
        return normalize_artist_name(artist.get("name") or artist.get("artist") or artist.get("channel"))
    return normalize_artist_name(artist)


def canonical_album_identity(album: Dict[str, Any]) -> str:
    album_id = _text(album.get("id") or album.get("album_id") or album.get("albumId"))
    if album_id:
        return album_id
    title_key = normalize_album_title(album.get("title") or album.get("album"))
    artist_key = normalize_artist_name(
        album.get("artist") or album.get("channel") or album.get("artist_name")
    )
    if title_key and artist_key:
        return f"{title_key}|{artist_key}"
    return title_key or artist_key


def canonical_title_artist_identity(track: Dict[str, Any]) -> str:
    title_key = normalize_track_title(track.get("title") or track.get("name"))
    artist_key = normalize_artist_name(
        track.get("channel") or track.get("artist") or track.get("author") or track.get("artist_name")
    )
    if title_key and artist_key:
        return f"{title_key}|{artist_key}"
    return title_key or artist_key


def canonical_track_identity(track: Dict[str, Any]) -> str:
    track_id = _text(track.get("id"))
    if track_id:
        return track_id
    return canonical_title_artist_identity(track)


def catalog_metadata_text(item: Dict[str, Any]) -> str:
    values: List[str] = []
    for key in (
        "title",
        "name",
        "artist",
        "artist_name",
        "channel",
        "author",
        "album",
        "album_title",
        "description",
        "source_name",
        "provider",
    ):
        value = item.get(key)
        if isinstance(value, dict):
            values.extend(str(entry or "") for entry in value.values())
        elif isinstance(value, (list, tuple, set)):
            values.extend(str(entry or "") for entry in value)
        else:
            values.append(str(value or ""))
    return normalize_catalog_text(" ".join(values))


def is_unofficial_catalog_item(item: Dict[str, Any]) -> bool:
    explicit = normalize_catalog_text(item.get("source_authority")).replace(" ", "_")
    if explicit == "search_only":
        return True
    if explicit in {"official", "canonical", "verified_catalog"}:
        return False
    text = catalog_metadata_text(item)
    return bool(_UNOFFICIAL_SOURCE_RE.search(text))


def catalog_source_authority(item: Dict[str, Any]) -> str:
    explicit = normalize_catalog_text(item.get("source_authority")).replace(" ", "_")
    if explicit in {
        "search_only",
        "official",
        "canonical",
        "verified_catalog",
    }:
        return explicit
    text = catalog_metadata_text(item)
    if is_unofficial_catalog_item(item):
        return "search_only"
    if _OFFICIAL_SOURCE_RE.search(text):
        return "official"
    if _text(item.get("album_id") or item.get("browseId") or item.get("artist_id")):
        return "canonical"
    if (
        _text(item.get("id"))
        and normalize_artist_name(
            item.get("artist") or item.get("artist_name") or item.get("channel")
        )
        and normalize_track_title(item.get("title") or item.get("name"))
        and normalize_catalog_text(
            item.get("provider") or item.get("source_name") or item.get("source")
        )
        in {"youtube music", "ytmusic", "artist catalog", "artist discography"}
    ):
        return "verified_catalog"
    return "unknown"


def canonical_source_identity(item: Dict[str, Any], *, entity_type: str) -> str:
    provider = normalize_catalog_text(
        item.get("provider") or item.get("source_name") or item.get("source") or "catalog"
    )
    if entity_type == "album":
        identity = canonical_album_identity(item)
    elif entity_type == "artist":
        identity = canonical_artist_identity(item)
    else:
        identity = canonical_track_identity(item)
    return f"{provider}:{identity}" if provider and identity else identity


def normalized_release_metadata(item: Dict[str, Any]) -> Dict[str, Any]:
    release_date = _display_text(
        item.get("release_date"),
        item.get("releaseDate"),
        item.get("date"),
        item.get("published_at"),
        item.get("publishedAt"),
        item.get("published"),
        item.get("upload_date"),
        item.get("uploadDate"),
        item.get("year"),
        item.get("release_year"),
    )
    if _COMPACT_DATE_RE.match(release_date):
        release_date = f"{release_date[:4]}-{release_date[4:6]}-{release_date[6:8]}"
    match = _YEAR_RE.search(release_date)
    return {
        "release_date": release_date,
        "release_year": int(match.group(0)) if match else None,
    }


def normalized_popularity(item: Dict[str, Any]) -> float:
    explicit = item.get("popularity")
    if explicit not in (None, ""):
        value = _number(explicit, 0.0)
        if value > 1.0:
            value = value / 100.0
        return round(max(0.0, min(value, 1.0)), 4)
    for key in ("view_count", "viewCount", "views", "play_count", "playCount", "plays"):
        value = _number(item.get(key), 0.0)
        if value > 0:
            # Log scaling keeps viral tracks from flattening every other item.
            return round(max(0.0, min(math.log10(value + 1.0) / 9.0, 1.0)), 4)
    return 0.0


def catalog_artist_graph_keys(item: Dict[str, Any]) -> List[str]:
    values: List[Any] = []
    for key in ("artist", "artist_name", "channel", "author", "name"):
        values.append(item.get(key))
    artists = item.get("artists")
    if isinstance(artists, list):
        for artist in artists:
            if isinstance(artist, dict):
                values.append(artist.get("name") or artist.get("title") or artist.get("artist"))
            else:
                values.append(artist)
    for key in ("related_artists", "similar_artists", "collaborators", "featured_artists"):
        extra = item.get(key)
        if isinstance(extra, dict):
            values.extend(extra.values())
        elif isinstance(extra, (list, tuple, set)):
            values.extend(extra)
        else:
            values.append(extra)
    output: List[str] = []
    seen = set()
    for value in values:
        normalized = normalize_artist_name(value)
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        output.append(normalized)
    return output


def normalized_audio_traits(item: Dict[str, Any]) -> Dict[str, float]:
    axes = item.get("audio_traits") or item.get("mood_axes") or {}
    axes = axes if isinstance(axes, dict) else {}
    output: Dict[str, float] = {}
    for key in ("energy", "drive", "calmness", "softness", "darkness", "danceability", "valence"):
        raw = axes.get(key, item.get(key))
        if raw in (None, ""):
            continue
        output[key] = round(max(0.0, min(_number(raw), 1.0)), 4)
    if output:
        return output
    text = catalog_metadata_text(item)
    if any(token in text for token in ("rock", "metal", "dance", "workout", "party", "upbeat", "anthem")):
        output["energy"] = 0.76
        output["drive"] = 0.72
    if any(token in text for token in ("acoustic", "piano", "ambient", "chill", "sleep", "soft", "ballad", "lo fi", "lofi")):
        output["calmness"] = 0.72
        output["softness"] = 0.7
        output.setdefault("energy", 0.32)
    if any(token in text for token in ("instrumental", "soundtrack", "score", "study")):
        output["instrumentalness"] = 0.74
        output.setdefault("calmness", 0.62)
    if any(token in text for token in ("funk", "disco", "dance", "club", "groove")):
        output["danceability"] = 0.74
    return output


def _shared_catalog_metadata(item: Dict[str, Any], *, entity_type: str) -> Dict[str, Any]:
    release = normalized_release_metadata(item)
    popularity = normalized_popularity(item)
    return {
        **release,
        "language": normalize_catalog_language(item.get("language")),
        "region": normalize_catalog_region(item.get("region")),
        "popularity": popularity,
        "audio_traits": normalized_audio_traits(item),
        "artist_graph_keys": catalog_artist_graph_keys(item),
        "source_authority": catalog_source_authority(item),
        "canonical_source_identity": canonical_source_identity(
            item,
            entity_type=entity_type,
        ),
    }


def normalized_track_payload(track: Dict[str, Any]) -> Dict[str, Any]:
    artist_name = _display_text(track.get("channel"), track.get("artist"), track.get("author"))
    album_title = _display_text(track.get("album"))
    payload = dict(track)
    payload.update(
        {
            "artist_name": artist_name,
            "album_title": album_title,
            "normalized_title": normalize_track_title(track.get("title") or track.get("name")),
            "normalized_artist_name": normalize_artist_name(artist_name),
            "normalized_album_title": normalize_album_title(album_title),
            "canonical_track_identity": canonical_track_identity(track),
            "canonical_title_artist_identity": canonical_title_artist_identity(track),
            **_shared_catalog_metadata(track, entity_type="track"),
        }
    )
    return payload


def normalized_artist_payload(artist: Dict[str, Any]) -> Dict[str, Any]:
    name = _display_text(artist.get("name"), artist.get("artist"), artist.get("channel"))
    payload = dict(artist)
    payload.update(
        {
            "name": name,
            "normalized_name": normalize_artist_name(name),
            "canonical_artist_identity": canonical_artist_identity(artist),
            **_shared_catalog_metadata(artist, entity_type="artist"),
        }
    )
    return payload


def normalized_album_payload(album: Dict[str, Any]) -> Dict[str, Any]:
    title = _display_text(album.get("title"), album.get("album"))
    artist_name = _display_text(album.get("artist"), album.get("channel"), album.get("artist_name"))
    payload = dict(album)
    payload.update(
        {
            "title": title,
            "artist_name": artist_name,
            "normalized_title": normalize_album_title(title),
            "normalized_artist_name": normalize_artist_name(artist_name),
            "canonical_album_identity": canonical_album_identity(album),
            **_shared_catalog_metadata(album, entity_type="album"),
        }
    )
    return payload


def _dedupe_rows(rows: Sequence[Dict[str, Any]], key_name: str) -> List[Dict[str, Any]]:
    deduped: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        key = _text(row.get(key_name))
        if not key:
            continue
        deduped[key] = dict(row)
    return list(deduped.values())


def cache_tracks(tracks: Iterable[Dict]) -> None:
    rows = []
    for track in tracks or []:
        if not isinstance(track, dict):
            continue
        track_id = _text(track.get("id"))
        if not track_id:
            continue
        normalized = normalized_track_payload(track)
        rows.append(
            {
                "track_id": track_id,
                "title": _display_text(track.get("title"), track.get("name")),
                "artist_name": normalized.get("artist_name") or "",
                "album_title": normalized.get("album_title") or "",
                **normalized,
            }
        )
    upsert_catalog_rows(
        table="catalog_tracks",
        key_name="track_id",
        rows=_dedupe_rows(rows, "track_id"),
    )


def cache_artists(artists: Iterable[Dict]) -> None:
    rows = []
    for artist in artists or []:
        if not isinstance(artist, dict):
            continue
        artist_id = _text(artist.get("id"))
        if not artist_id:
            continue
        normalized = normalized_artist_payload(artist)
        rows.append({"artist_id": artist_id, **normalized})
    upsert_catalog_rows(
        table="catalog_artists",
        key_name="artist_id",
        rows=_dedupe_rows(rows, "artist_id"),
    )


def cache_albums(albums: Iterable[Dict]) -> None:
    rows = []
    for album in albums or []:
        if not isinstance(album, dict):
            continue
        album_id = _text(album.get("id"))
        if not album_id:
            continue
        normalized = normalized_album_payload(album)
        rows.append({"album_id": album_id, **normalized})
    upsert_catalog_rows(
        table="catalog_albums",
        key_name="album_id",
        rows=_dedupe_rows(rows, "album_id"),
    )


def cache_search_payload(
    *,
    tracks: List[Dict],
    artists: List[Dict],
    albums: List[Dict],
) -> None:
    cache_tracks(tracks)
    cache_artists(artists)
    cache_albums(albums)
