[package]
name = "auralis_ingestion"
version = "0.1.0"
edition = "2021"

[lib]
name = "auralis_ingestion"
crate-type = ["cdylib", "staticlib"]

[dependencies]
rusty_ytdl = { version = "0.7.3", default-features = false, features = ["search", "rustls-tls"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.37.0", features = ["full", "rt-multi-thread", "macros"] }
libc = "0.2"
